### ISSUE TITLE
Error I received

### ISSUE THREAD

**Issue by HuiqingSun** [alessiakz/INFO550_Final_Project#1]
There was an error said :
"Error in select(., location, total_vaccinations, total_vaccinations_per_hundred, :
object 'data_clean' not found
Calls: %>% -> ggplot -> filter -> select" for code/02_chart.R when I make final_project_covid.html. I looked through your code for 02_chart, and it turns out that your data named data when you readRDS, but your chart was created from data_clean.

**Comment by alessiakz** [comment]
Thank you! The issue has been resolved now
