### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by benkeser** [alessiakz/INFO550_Final_Project#3]
I'm going to hold off on grading your final submission, because it looks like you have an error in the file path in your Makefile, `final_project` vs. `final_report`. Not sure if you want to fix this ahead of the project submission deadline.

Please respond to this issue indicating when I should continue grading.

**Comment by alessiakz** [comment]
Hi, I'd like to resubmit and fix this issues before grading. Thank you for bringing this issue to my attention!

**Comment by alessiakz** [comment]
I believe I have resolved this typo now! Thank you for your help!
