### ISSUE TITLE
remaining issues

### ISSUE THREAD

**Issue by benkeser** [alessiakz/INFO550_Final_Project#4]
There are still 2 issues remaining that we discussed in class:
1. The [target](https://github.com/alessiakz/INFO550_Final_Project/blob/300763cdcc9c7e88e2fd739f48c4ba18c4c326ab/Makefile#L36) for building the report using `docker run` should not have any pre-requisites.
2. The [`docker run` command](https://github.com/alessiakz/INFO550_Final_Project/blob/300763cdcc9c7e88e2fd739f48c4ba18c4c326ab/Makefile#L37) needs to reference the image as it was tagged when you pushed it to docker hub. So it should look something like `docker run -v <...> <dockerhub_user_name>/<image_name>`

I will hold off on grading until tomorrow after due date. Or until I hear from you again.

**Comment by alessiakz** [comment]
I'm sorry! I had forgotten to update those after we had discussed in class.

Everything should be up-to-date and working now. Thank you again for letting me know about these issues!
